apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: secure-token-service
    sync:
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
          - rockcraft.yaml
    platforms: ["linux/amd64"]
manifests:
  kustomize:
    paths:
    - k8s
deploy:
  helm:
    releases:
    - name: valkey
      createNamespace: true
      namespace: data
      remoteChart: oci://registry-1.docker.io/bitnamicharts/valkey
      setValues:
        auth.enabled: "false"
        fullnameOverride: "valkey"
        architecture: "standalone"
        networkPolicy.enabled: "false"
    - name: postgresql
      createNamespace: true
      namespace: data
      remoteChart: oci://registry-1.docker.io/bitnamicharts/postgresql
      setValues:
        auth.username: "stsuser"
        auth.password: "stspassword"
        auth.database: "sts"
        fullnameOverride: "postgresql"
        primary.persistence.enabled: "true"
        primary.persistence.size: "1Gi"
        primary.networkPolicy.enabled: "false"
  kubectl: {}
profiles:
- name: istio
  manifests:
    kustomize:
      paths:
      - k8s/istio
  deploy:
    helm:
      releases:
        # 1. Base CRDs
        - name: istio-base
          remoteChart: base
          repo: https://istio-release.storage.googleapis.com/charts
          namespace: istio-system
          createNamespace: true
          wait: true

        # 2. Control Plane (set to ambient profile)
        - name: istiod
          remoteChart: istiod
          repo: https://istio-release.storage.googleapis.com/charts
          namespace: istio-system
          setValues:
            profile: ambient
          wait: true

        # 3. CNI Node Agent (required for ambient mode traffic)
        - name: istio-cni
          remoteChart: cni
          repo: https://istio-release.storage.googleapis.com/charts
          namespace: istio-system
          setValues:
            profile: ambient
          wait: true

        # 4. Ztunnel (the node-level proxy)
        - name: ztunnel
          remoteChart: ztunnel
          repo: https://istio-release.storage.googleapis.com/charts
          namespace: istio-system
          wait: true        
        
        # 5. istio-ingressgateway (the node-level proxy)
        - name: istio-ingressgateway
          remoteChart: gateway 
          repo: https://istio-release.storage.googleapis.com/charts
          namespace: istio-system
          wait: true        
    kubectl: {}

