apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: secure-token-service
build:
  artifacts:
  - image: secure-token-service
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
    - k8s
deploy:
  helm:
    releases:
    - name: valkey
      remoteChart: oci://registry-1.docker.io/bitnami/charts/valkey
      version: 2.1.2 # Pinning a recent version
      setValues:
        auth.enabled: "false"
        fullnameOverride: "valkey"
        architecture: "standalone"
  kubectl: {}
