// Copyright 2026 Canonical Ltd.
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/v1/sts.proto

package stsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionCookie string                 `protobuf:"bytes,1,opt,name=session_cookie,json=sessionCookie,proto3" json:"session_cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRequest) Reset() {
	*x = ExchangeRequest{}
	mi := &file_api_proto_v1_sts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRequest) ProtoMessage() {}

func (x *ExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_sts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_sts_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeRequest) GetSessionCookie() string {
	if x != nil {
		return x.SessionCookie
	}
	return ""
}

type ExchangeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // Raw upstream IdP access token (JWT)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeTokenRequest) Reset() {
	*x = ExchangeTokenRequest{}
	mi := &file_api_proto_v1_sts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeTokenRequest) ProtoMessage() {}

func (x *ExchangeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_sts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeTokenRequest.ProtoReflect.Descriptor instead.
func (*ExchangeTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_sts_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // Signed Internal JWT
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`      // Seconds until expiration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeResponse) Reset() {
	*x = ExchangeResponse{}
	mi := &file_api_proto_v1_sts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResponse) ProtoMessage() {}

func (x *ExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_sts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_sts_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ExchangeResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type RevokeUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeUserRequest) Reset() {
	*x = RevokeUserRequest{}
	mi := &file_api_proto_v1_sts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUserRequest) ProtoMessage() {}

func (x *RevokeUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_sts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUserRequest.ProtoReflect.Descriptor instead.
func (*RevokeUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_sts_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RevokeUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeUserResponse) Reset() {
	*x = RevokeUserResponse{}
	mi := &file_api_proto_v1_sts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUserResponse) ProtoMessage() {}

func (x *RevokeUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_sts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUserResponse.ProtoReflect.Descriptor instead.
func (*RevokeUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_sts_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_v1_sts_proto protoreflect.FileDescriptor

const file_api_proto_v1_sts_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/v1/sts.proto\x12\x06sts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\x0fExchangeRequest\x12%\n" +
	"\x0esession_cookie\x18\x01 \x01(\tR\rsessionCookie\",\n" +
	"\x14ExchangeTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"T\n" +
	"\x10ExchangeResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\",\n" +
	"\x11RevokeUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x12RevokeUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf2\x01\n" +
	"\x14SecurityTokenService\x12D\n" +
	"\x0fExchangeSession\x12\x17.sts.v1.ExchangeRequest\x1a\x18.sts.v1.ExchangeResponse\x12G\n" +
	"\rExchangeToken\x12\x1c.sts.v1.ExchangeTokenRequest\x1a\x18.sts.v1.ExchangeResponse\x12K\n" +
	"\x12RevokeUserSessions\x12\x19.sts.v1.RevokeUserRequest\x1a\x1a.sts.v1.RevokeUserResponseB>Z<github.com/canonical/secure-token-service/api/proto/v1;stsv1b\x06proto3"

var (
	file_api_proto_v1_sts_proto_rawDescOnce sync.Once
	file_api_proto_v1_sts_proto_rawDescData []byte
)

func file_api_proto_v1_sts_proto_rawDescGZIP() []byte {
	file_api_proto_v1_sts_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_sts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_sts_proto_rawDesc), len(file_api_proto_v1_sts_proto_rawDesc)))
	})
	return file_api_proto_v1_sts_proto_rawDescData
}

var file_api_proto_v1_sts_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_v1_sts_proto_goTypes = []any{
	(*ExchangeRequest)(nil),      // 0: sts.v1.ExchangeRequest
	(*ExchangeTokenRequest)(nil), // 1: sts.v1.ExchangeTokenRequest
	(*ExchangeResponse)(nil),     // 2: sts.v1.ExchangeResponse
	(*RevokeUserRequest)(nil),    // 3: sts.v1.RevokeUserRequest
	(*RevokeUserResponse)(nil),   // 4: sts.v1.RevokeUserResponse
}
var file_api_proto_v1_sts_proto_depIdxs = []int32{
	0, // 0: sts.v1.SecurityTokenService.ExchangeSession:input_type -> sts.v1.ExchangeRequest
	1, // 1: sts.v1.SecurityTokenService.ExchangeToken:input_type -> sts.v1.ExchangeTokenRequest
	3, // 2: sts.v1.SecurityTokenService.RevokeUserSessions:input_type -> sts.v1.RevokeUserRequest
	2, // 3: sts.v1.SecurityTokenService.ExchangeSession:output_type -> sts.v1.ExchangeResponse
	2, // 4: sts.v1.SecurityTokenService.ExchangeToken:output_type -> sts.v1.ExchangeResponse
	4, // 5: sts.v1.SecurityTokenService.RevokeUserSessions:output_type -> sts.v1.RevokeUserResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_sts_proto_init() }
func file_api_proto_v1_sts_proto_init() {
	if File_api_proto_v1_sts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_sts_proto_rawDesc), len(file_api_proto_v1_sts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_sts_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_sts_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_sts_proto_msgTypes,
	}.Build()
	File_api_proto_v1_sts_proto = out.File
	file_api_proto_v1_sts_proto_goTypes = nil
	file_api_proto_v1_sts_proto_depIdxs = nil
}
