apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- configmap.yaml
- secret.yaml
- migration-cronjob.yaml

commonLabels:
  app: secure-token-service

images:
- name: secure-token-service
