apiVersion: v1
kind: Secret
metadata:
  name: secure-token-service-secret
  labels:
    app: secure-token-service
type: Opaque
stringData:
  # Cache credentials
  CACHE_PASSWORD: ""
  CACHE_DB: "0"
  
  # Cookie encryption keys (REPLACE IN PRODUCTION!)
  COOKIE_HASH_KEY: "0123456789012345678901234567890123456789012345678901234567890123"
  COOKIE_BLOCK_KEY: "01234567890123456789012345678901"
  
  # Database credentials
  DATABASE_URL: "postgres://stsuser:stspassword@postgresql.default.svc.cluster.local:5432/sts?sslmode=disable"
  
  # OIDC Secrets (REPLACE WITH ACTUAL VALUES!)
  OIDC_CLIENT_ID: "848498417150-sft0usjh085j4gr0f9tf4tphrqlkbm9r.apps.googleusercontent.com"
  OIDC_CLIENT_SECRET: "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"

