name: unit test
run-name: Unit test steps for ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: '1.26'

      - name: Run vulnerability check
        run: make govulncheck

      - name: Install Podman
        uses: redhat-actions/podman-install@main

      - name: Setup podman for rootless (standard GitHub runner user)
        run: systemctl --user enable --now podman.socket

      - name: Build Go code
        run: make test
        env:
          GO_TEST_PARALLEL: 10
          DOCKER_HOST: "unix://$XDG_RUNTIME_DIR/podman/podman.sock"

      - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        with:
          files: ./coverage.out

      - name: Upload Go test results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: Go-results
          path: test.json
